name: riverpod_tutorials
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.2
  http: ^0.13.5
  go_router: ^6.5.5
  flutter_smartlook: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
